### ISSUE TITLE
Need help with adding Catppuccin colorscheme module

### ISSUE THREAD

**Issue by hcwf** [NixNeovim/NixNeovim#104]
I wrote a module for adding the Catppuccin colorscheme to NixNeovim but the colorscheme never gets added to the init.lua file, therefore loading it with vim.cmd fails.
I'd appreciate it if someone could look over my code and tell me where I'm overlooking or missing things.

The module can be found [here](https://github.com/hcwf/NixNeovim/blob/add-catppuccin/src/colorschemes/catppuccin.nix).

This is the error I get when starting nvim:
```
Error detected while processing /home/hendrik/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_editor.lua:0: /home/hendrik/.config/nvim/init.lua..nvim_exec2() called at /home/hendrik/.config/
nvim/init.lua:0: Vim(colorscheme):E185: Cannot find color scheme 'catppuccin'
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /home/hendrik/.config/nvim/init.lua:236: in main chunk
Press ENTER or type command to continue
```

This is the line in init.lua:
```
vim.cmd([[colorscheme catppuccin]])
```

As the last line of extraConfigLua in the module is actually present in the init.lua, I suspect the first line that sets up the colorscheme fails silently. Any input on how to further debug this is appreciated, I'm super new to Nix and Neovim/LUA.

**Comment by jooooscha** [comment]
First of, thanks for your work and that you support this project.
Could I ask you to do a draft PR? That would allow me to add comments to you specific lines of your code. :)

And yes, I should finally take the time to write some good documentation for this 😅

**Comment by hcwf** [comment]
Thanks for your reply, I did a draft PR here -> #105
