### ISSUE TITLE
Telescope extraConfig does not seem to work

### ISSUE THREAD

**Issue by YanniPapandreou** [NixNeovim/NixNeovim#34]
Hi, first thanks for creating and maintaining this, I have been enjoying using it!

I am new to nix so not sure if I am doing something wrong. But it seems like the option `programs.nixneovim.plugins.telescope.extraConfig` doesn't do anything to the configuration of neovim. I checked the source code and it seems to not be put into `extraConfigLua` in `plugins/telescope/default.nix`, this file has:

```nix
extraConfigLua =
    ''
      local telescope = require('${name}')
          telescope.setup {
            extensions = ${ extensions.config }
          }
          ${ concatStringsSep "\n    " extensions.loadString } '';
```
I tried to modify this to somehow add `cfg.extraConfig` to the lua string but I can't seem to figure out how to combine it with extensions. Am I missing something?

**Comment by jooooscha** [comment]
Sorry, for taking so long to respond.

Currently, you have to first disable `defaultRequrie` in order for `extraConfigLua` to be used. I recognize that this is not a very intuitive interface. I will think about, how to improve this.

Also, I recommend using `extraLua.pre` or `extraLua.post`, which gives you more control over where the lua code will be placed relative to the default `require` statement.

I know that this project is currently documented poorly, but I am, currently, the only maintainer and do not have too much time to put into this.

**Comment by jooooscha** [comment]
Ignore my previous comment, I misread your issue.

I will look into it

**Comment by jooooscha** [comment]
Should be fixed now. I have taken this occasion to clean up the whole project a bit. Please report back if that breaks anything

**Comment by YanniPapandreou** [comment]
@jooooscha thanks a lot for looking into this! I will check it out and let you know if i run into any issues :)

**Comment by jooooscha** [comment]
Seems like it is working for you, now. However, I have found a new problem with my solution, so I reworked it again. I hope this does not unfix your problem. So please report if it does.

**Comment by YanniPapandreou** [comment]
Thanks for letting me know, I've switched my config for neovim to just use the home-manager module so I am no longer using this at the moment!
