### ISSUE TITLE
Infinite recursion on minimal flake

### ISSUE THREAD

**Issue by jalil-salame** [NixNeovim/NixNeovim#52]
I hit infinite recursion on a minimal flake:

```nix
# flake.nix
{
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";

    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    nixneovim.url = "github:nixneovim/nixneovim";
  };

  outputs = {
    self,
    nixpkgs,
    home-manager,
    nixneovim,
    ...
  } @ specialArgs: let
    system = "x86_64-linux";
    pkgs = import nixpkgs {
      inherit system;
      overlays = [nixneovim.overlays.default];
    };
  in
    {
      nixosConfigurations.gemini = nixpkgs.lib.nixosSystem {
        inherit system specialArgs pkgs;
        modules = [
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.jalil = import ./home.nix;
          }
        ];
      };
    };
}
```

```nix
# home.nix
{
  configuration,
  pkgs,
  nixneovim,
  ...
}:
{
  imports = [nixneovim.nixosModules.default];
  home.username = "jalil";
  home.stateVersion = "22.11";
  programs.nixneovim = { enable = true;};
}
```

Commenting out `imports = [nixneovim.nixosModules.default];` fixes it (but then I can't use nixneovim, ofc)

I am probably doing something wrong but the documentation is not clear on where to put the `import`, I have tried importing inside `home-manager.nixosModules.home-manager`, but then `porgrams.nixneovim` doesn't have acces to the `neovim` home-manager module.

I am on NixOS unstable.

If you could show me a minmal working flake, then I can probably figure out the rest on my own and submit a PR updating the documentation.

**Comment by jooooscha** [comment]
I import nixneovim.nixosModules.homeManager-22-11 in `users.<user>.imports`.

I will look into it. Thanks for reporting

**Comment by jalil-salame** [comment]
I think the problem is in `inherit specialArgs`, I ended up changing my NixOS config until it fixed itself but I didn't understand what was causing the recursion.

**Comment by jooooscha** [comment]
That's sometimes hard to know with nix.
Please report if you think this is a problem with NixNeovim.

Closing for now
