### ISSUE TITLE
doc request: Add guide how to use this in home-manager

### ISSUE THREAD

**Issue by michaelCTS** [NixNeovim/NixNeovim#53]
For those of us that are new to nix and using home-manage, how would one use this package in home-manager?

**Comment by jooooscha** [comment]
The README states:

> import the module to your Home Manager [...] configuration

I think this it unambiguously, and you should look into the home manager docs if it does not help you.
I know NixOS and home-manager could be better documented, but that is not the scope of this repo.

In my case, I import a module into my `nixosSystem` in which I declare `home-manager.users.<user>.imports = [ nixneovim.nixosModules.home-manager-22-11]`

I hope that helps

**Comment by michaelCTS** [comment]
I found a way to do it, so I'll just share it here in case somebody else happens to run in to the same issue:

```nix
# Maybe also possible to add it as a channel?
neovimPlugins = import (pkgs.fetchFromGitHub {
        owner = "NixNeoVim";
        repo = "NixNeovimPlugins";
        rev = "7710e6f";
        sha256 = "sha256-cS6C0FJk+jKIWo84oQ62wxv6kIoXWXDlFSHvTnnZP74=";
    });
customPkgs = import <nixpkgs> {
  overlays = [
    neovimPlugins.overlays.default
  ];
};
```
