### ISSUE TITLE
Add `viAlias`/`vimAlias` to options

### ISSUE THREAD

**Issue by mirkolenz** [NixNeovim/NixNeovim#57]
Currently, this module does not supply options to provide `viAlias` and `vimAlias`. I saw that in https://github.com/NixNeovim/NixNeovim/blob/main/nixneovim.nix#L251 you enable the builtin neovim modules of home manager or nixos. Since both provide said options, could you expose them through the `NixNeovim` module? That would be great!

**Comment by jooooscha** [comment]
Implemented in #5e47f27.

Thanks for reporting

**Comment by mirkolenz** [comment]
Thank you for adding these options in such a short amount of time!
