### ISSUE TITLE
bug: rust-tools no way to set server settings

### ISSUE THREAD

**Issue by jalil-salame** [NixNeovim/NixNeovim#61]
https://github.com/NixNeovim/NixNeovim/blob/708e9fb7ddfcef4b750c5d90a9c98f399c84c171/plugins/languages/rust.nix#L126-L133

As stated in the top comment, this field of the rust tools configuration accepts settings from `plugins/nvim-lsp`, as it currently stands, there is no way to configure the onAttach function (ideally it would inherit the one set in nvim-lsp, and have an onAttachExtra same as all the other lsp servers)

**Comment by jooooscha** [comment]
I am not completely sure what you mean. Could specify what settings you want to have in `rust.nix`?
For example, you could give me an example config.

**Comment by jalil-salame** [comment]
Sorry for the delay, hare is an example:

```nix
{
  lsp.enable = true;
  lsp.onAttach = "-- custom lsp code"; # I need this
  rust-tools.enable = true;
  rust-tools.server.onAttachExtra = "-- custom rust-tools code"; # I don't need this but it makes sense
}
```

Lua:

```lua
-- LSP
local function __on_attach(...)
  -- custom lsp code
end
local __setup = { on_attach = __on_attach }
require("lspconfig")["json_ls"].setup(__setup)
-- Rust Tools
require("rust-tools).setup {
  -- ...
  ["server"] = {
    ["standalone"] = true,
    ["on_attach"] = function(...)
      -- custom lsp code
      -- custom rust-tools code
    end
  }
}
```

**Comment by jooooscha** [comment]
Thanks, I will look into it

**Comment by VincentBerthier** [comment]
Damn, I have the same problem (at the same place, but I know there are other cases).
Basically the issue is that anything we set here, is put in the init.lua file as a string, where it’s supposed to be code.

Maybe an option could be to just add some kind of formatting trick to those fields? Something like "whatever" is a string, but "`whatever`" is code for example (or with three backticks if there’s a compatibility risk for some reason)?
That way you’d just need to modify the code in one place on your side, wherever the values are written in the init.lua.

**Comment by jooooscha** [comment]
Ok, in the next days I will have time to look at this, but I am still not sure what exactly you need.

You need a `server.on_attach` option, that will end up in `rust-tools` lua config like this, right?

```
 server = {
    on_attach = ...
  },
```

**Comment by jalil-salame** [comment]
> Ok, in the next days I will have time to look at this, but I am still not sure what exactly you need.
> 
> You need a `server.on_attach` option, that will end up in `rust-tools` lua config like this, right?
> 
> ```
>  server = {
>     on_attach = ...
>   },
> ```
> 

Yup, that is the exact issue.

Ideally, whatever I set for the on_attach of the LSP, will also be set on rust-tools (I set LSP specific keybindings there).

So what I **need** is: a way to set on_attach.

And what I think _would_ be nice, is for rust-tools to hook into the LSP configuration and inherit the onAttach and onAttachExtra options from the LSP configuration.

**Comment by jalil-salame** [comment]
I have given it a try, but after scratching my head for 30 minutes I couldn't think of a way to get either to work.

**Comment by jooooscha** [comment]
You can set `lspconfig.onAttach` (formerly `lsp.onAttach`), where you can put code that is placed in every onAtach function of every server. Additionally, you can put code in `lspconfig.servers.<server-name>.onAttachExtra`. This code will only be loaded in the `onAttach` function of that specific server.

Does this not satisfy your "need"-problem?

The "would-be-nice"-problem should be implementable based on that.

**Comment by jalil-salame** [comment]
> You can set `lspconfig.onAttach` (formerly `lsp.onAttach`), where you can put code that is placed in every onAtach function of every server. Additionally, you can put code in `lspconfig.servers.<server-name>.onAttachExtra`. This code will only be loaded in the `onAttach` function of that specific server.
> 
> Does this not satisfy your "need"-problem?
> 
> The "would-be-nice"-problem should be implementable based on that.

Exactly, the problem is rust-tools doesn't interoperate with that, and I have no idea how to get it to do that.

**Comment by jooooscha** [comment]
If I understand the documentation of `rust-tools` correctly you can use this option:

```
-- all the opts to send to nvim-lspconfig
  -- these override the defaults set by rust-tools.nvim
  -- see https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#rust_analyzer
  server = {
    -- standalone file support
    -- setting it to false may improve startup time
    standalone = true,
  }, -- rust-analyzer options
```

This option is already available in `rust-tools`

**Comment by jalil-salame** [comment]
> This option is already available in the current `rust-tools` module

```log
error: The option `home-manager.users.user1.programs.nixneovim.plugins.rust-tools.server.on_attach' does not exist.
```

I am using `github:NixNeovim/NixNeovim/6942bb144608ff955b51d40ef97f0567b44b7698`, so AFAIK, it doesn't currently work, adding it to the module would be nice, but it wouldn't integrate with the lspconfig plugin, which would be nice.

**Comment by jooooscha** [comment]
Ok, I have created a PR here: #78. Could you check if that solves your problem?
