### ISSUE TITLE
Docs make flake check fail

### ISSUE THREAD

**Issue by jalil-salame** [NixNeovim/NixNeovim#69]
`nix flake check` is complaining about these lines:

https://github.com/NixNeovim/NixNeovim/blob/main/flake.nix#L53-L56

Says it is a function instead of an attr set, I might've introduced it inside of the augroups PR or the flake utils PR, I'm not sure...

**Comment by jooooscha** [comment]
Did you just run `nix flake check`? I just pulled `main` and got no errors.

Also, the `docs` packages should not be included in the checks

**Comment by jalil-salame** [comment]
I was running `nix flake check` on the augroups PR

**Comment by jooooscha** [comment]
Then, you should have commented that on the PR. Please continue discussion there.

Ref: #66
