### ISSUE TITLE
ruff-lsp causing problems

### ISSUE THREAD

**Issue by jalil-salame** [NixNeovim/NixNeovim#81]
I am getting `error: ruff-lsp should use `buildPythonPackage` or `toPythonModule` if it is to be part of the Python packages set.`

I am guessing it is because of this:

https://github.com/NixNeovim/NixNeovim/blob/main/src/plugins/_lspconfig-modules/servers.nix#L111-L116
```nix
ruff-lsp = {
  languages = "Python";
  serverName = "ruff_lsp";
  packages = optional (builtins.hasAttr "ruff-lsp" pkgs) [ ruff-lsp ] # on unstable
  ++ optional (builtins.hasAttr "ruff-lsp" python310Packages) [ python310Packages.ruff-lsp ]; # on 23.05
};
```

This is the failing workflow: https://github.com/jalil-salame/NixOsConfig/actions/runs/6662969631/job/18108133605

I assume `python310Packages.ruff-lsp` is being selected on unstable for some reason? But I am not sure...

On 23.05 it exists https://search.nixos.org/packages?query=ruff-lsp

But it doesn't in unstable: https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=ruff-lsp

So I don't think it should be a problem?

**Comment by jooooscha** [comment]
That's a tricky one. It must have something to do with the fact that `ruff-lsp` is under `python311Packges` in 23.05 but directly in `pkgs` in unstable. I am not completely sure what has changed besides that.

I will look into it, but it will probably take some time. i am sorry for the inconvenience

**Comment by jalil-salame** [comment]
I barely use Python so I just deactivated `ruff-lsp`. It doesn't affect me.

I tried adding a test to check if you can install all lspconfig servers, but I couldn't understand the code...

**Comment by jooooscha** [comment]
Maybe I should write documentation for it. But in short, for now: I have some checks for the functions, those are in `function-tests.nix`. They are very basic and probably not that important.

All other checks are in `integration/`. Plugins are in `plugins/` and so on. They all contain a module that you can use to set your `NixNeovim` configs. For example, they all set `nixneovim.enable = true`. To enable a plugin, you can just use the normal `nixneoivm.plugins.<plugin-name>.enable = true` options.

The unusual part is the `nmt.scipt` option. This defines a bash script that you can use to run some checks. For example, in almost every test I call the `assertDif` bash function (defined in the `nmt` library), which compares the generated vim config (in the tests called `init.lua-expected`) with the text given in the second argument. So basically, we check that the generated config is what we expect.

A fairly simple example should be the `wilder.nix` test.

All these modules are then combined to a list of modules in `tests.nix` and "run" by "calling" `tests.build`

**Comment by jooooscha** [comment]
I think I found the problem. I have pushed a commit at 1200dffaac6046ba734f35f0977e2034e9deca7c, could you check if this solves your problem?

The current method of determining the correct package is flawed and selected the wrong package. I have changed it to use the  internal `state` variable.
